#%RAML 1.0 DataType
properties:
  name:
    type: string
  productid:
    type:integer
  categoryid:
    type: integer
  description:
    type: string
  video_url:
    type: string 
  price: 
    type: integer 
